[package]
name = "notifier"
version = "0.1.0"
authors = ["Utkarsh Raj <clearnote01@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "^3"
regex = "1"
clap = "3.0.0-beta.1"
